run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  test: true
  skip-dirs:
    - vendor$
    - build$

output:
  print-issued-lines: true
  print-linter-name: true

service:
  golangci-lint-version: 1.16.x