version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
  pre_build:
    commands:
      - make format-check
      - make lint
  build:
    commands:
      - make build-stripped
      - rm buildspec.yml
      - mv terraform/stack/buildspec.yml .

artifacts:
  files:
    - app
    - terraform/stack/**/*
    - buildspec.yml