aws_region = "us-east-1"
application_name = "aws-go-play"
github_user = "justinricheson"
github_repository = "aws-go-play"
github_branch = "master"
build_image = "aws/codebuild/amazonlinux2-x86_64-standard:latest"
