version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - git clone https://github.com/elasticbyte/hashipm.git
      - ln -s $PWD/hashipm/hashipm.bash /usr/local/bin/hashipm
      - export HASHIPM_ROOT=$PWD/hashipm
      - hashipm get terraform

  pre_build:
    commands:
      - AWS_CREDS=`aws sts assume-role --role-arn $${TERRAFORM_ROLE} --role-session-name codebuild`
      - export AWS_ACCESS_KEY_ID=`echo "$${AWS_CREDS}" | jq -r '.Credentials.AccessKeyId'`
      - export AWS_SECRET_ACCESS_KEY=`echo "$${AWS_CREDS}" | jq -r '.Credentials.SecretAccessKey'`
      - export AWS_SESSION_TOKEN=`echo "$${AWS_CREDS}" | jq -r '.Credentials.SessionToken'`
      - export TF_IN_AUTOMATION=1
  build:
    commands:
      - cd terraform/stack
      - terraform init -input=false
      - terraform apply -input=false -var-file="$(pwd)/stack.tfvars"
